[project]
name = "nnlib"
version = "0.1.0"
description = "A library of neural network architectures for acoustics-informed applications."
readme = "README.md"
authors = [
    { name = "Sturla Njardarson", email = "sturlanjardarson@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "ax-platform>=1.1.2",
    "diffrax>=0.7.0",
    "equinox>=0.13.1",
    "ipdb>=0.13.13",
    "jax>=0.7.2",
    "jaxlib>=0.7.2",
    "matplotlib>=3.10.6",
    "optax>=0.2.6",
    "pyglet<2",
    "pytest>=8.4.2",
    "soap-jax",
    "tensorflow>=2.20.0",
    "torch>=2.8.0",
    "tqdm>=4.67.1",
    "trimesh>=4.8.3",
]

[build-system]
requires = ["uv_build>=0.8.21,<0.9.0"]
build-backend = "uv_build"

[tool.uv.sources]
soap-jax = { git = "https://github.com/haydn-jones/SOAP_JAX" }

